language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - npm test

deploy:
  provider: script
  script: 'echo "//registry.npmjs.org/:_authToken=${API_TOKEN}" > $HOME/.npmrc && npm publish --access=public'
  on:
    tags: true
  skip_cleanup: true

notifications:
  email: false
